theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "uptime"

[[block]]
block = "sound"

[[block]]
block = "music"
buttons = ["play"]

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
speed_up = false
speed_down = false

[[block]]
block = "temperature"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
interval = 1

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
